// @flow
declare module 'material-ui/AppBar' { declare var exports: any }
declare module 'material-ui/Button' { declare var exports: any }
declare module 'material-ui/Card' { declare var exports: any }
declare module 'material-ui/Checkbox' { declare var exports: any }
declare module 'material-ui/colors/blue' { declare var exports: any }
declare module 'material-ui/colors/teal' { declare var exports: any }
declare module 'material-ui/Dialog' { declare var exports: any }
declare module 'material-ui/Form' { declare var exports: any }
declare module 'material-ui/Grid' { declare var exports: any }
declare module 'material-ui/IconButton' { declare var exports: any }
declare module 'material-ui/Menu' { declare var exports: any }
declare module 'material-ui/Paper' { declare var exports: any }
declare module 'material-ui/Radio' { declare var exports: any }
declare module 'material-ui/styles' { declare var exports: any }
declare module 'material-ui/styles/createMuiTheme' { declare var exports: any }
declare module 'material-ui/styles/MuiThemeProvider' { declare var exports: any }
declare module 'material-ui/styles/palette' { declare var exports: any }
declare module 'material-ui/TextField' { declare var exports: any }
declare module 'material-ui/Toolbar' { declare var exports: any }
declare module 'material-ui/transitions/Slide' { declare var exports: any }
declare module 'material-ui/Typography' { declare var exports: any }
